# Generated by Django 2.1.2 on 2018-11-05 07:57

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('winner', models.IntegerField(blank=True)),
                ('board', django.contrib.postgres.fields.jsonb.JSONField()),
                ('borders', django.contrib.postgres.fields.jsonb.JSONField()),
                ('score', django.contrib.postgres.fields.jsonb.JSONField()),
                ('started_at', models.IntegerField()),
                ('ended_at', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
