# Generated by Django 2.1.2 on 2018-11-05 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181105_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameinfo',
            old_name='ended_at',
            new_name='endedAt',
        ),
        migrations.RenameField(
            model_name='gameinfo',
            old_name='started_at',
            new_name='startedAt',
        ),
    ]
